version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: carryon_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: carryon
      POSTGRES_PASSWORD: carryon_dev
      POSTGRES_DB: carryon_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
